#!/bin/sh

fname=$(basename "$0")
usage()
{
  echo "$fname [options] <operation>
[Global Operations]:
  list-files            List eligible files in data path. Shortcut 'lsf'
  cache-clear           Delete all cached keys. Shortcut 'cc'
  help                  Display help
  rm-file <file...>     Remove files. Shortcut 'rmf'
[File Operations]:
  ls [path]             List contents at given path
  tree                  List all contents
  create                Create a file or change key
  get <path...>         Get values of targets
  copy <path>           Copy the target value to clipboard. Shortcut 'x'
  set <path> <value>    Set directly the value of target
  file <path> <file>    Set the targetted value from file content
  add <path...>         Prompt for input value on paths
  new <path...>         Generate a random password at target
  rm <path...>          Delete targets
  mv <path...>          Move targets
  exec <cmd>            Execute the following command inside the archive.
  cached                Returns wether or not a key is currently cached. Shortcut 'ch'
  rm-cache              Delete the cached key for this file. Shortcut 'rmc'

[Config]:
 *Variable*              *Default value*                       *Description*
 ------------------------------------------------------------------------------------------------------------------------
  CONFIGFILE              '\$XDG_CONFIG_HOME/zpass/defaut.conf'  Path to the config file to load
  ZPASS_PATH              '\$XDG_DATA_HOME/zpass'                Folder containing password files
  ZPASS_CACHE_PATH        '\$XDG_CACHE_HOME/zpass'               Path used for caching keys
  ZPASS_FILE              'default'                             File to use for operations
  ZPASS_KEY                                                     Key to use for encrypting/decrypting files
  ZPASS_KEY_CACHE_TIME    '60'                                  Time a key stays in cache for decrypting, in seconds
  ZPASS_CLIPBOARD_TIME    '30'                                  Time until clipboard gets cleared after copy, in seconds
  ZPASS_UNK_OP_CALL       'copy'                                Operation to call on unrecognized first argument
  ZPASS_RAND_LEN          '20'                                  Length of random passwords generated by 'new'
  ZPASS_RAND_SET          'a-zA-Z0-9\!-.'                       Character set to use for 'new' generation
  ZPASS_REMOTE_METHOD     'scp'                                 Method to use for remote file. scp/sftp/ftps/webdav
  ZPASS_REMOTE_ADDR                                             Server the file is on
  ZPASS_REMOTE_PORT                                             Server port
  ZPASS_SSH_ID                                                  SSH private key to use for scp/sftp
  ZPASS_REMOTE_USER                                             User for login
  ZPASS_REMOTE_PASSWORD                                         Password for ftps/webdav login. Not for SSH
  ZPASS_PRIORITIZE_CLI                                          Key prompt will always be done on CLI if stdin is a tty
  ZPASS_COPY_ON_EDIT                                            Set to true, edit operations will copy the affected element
                                                                  > set , file , add , new

All operations can be shortened to their first char unless specified
Unknown first argument will perform the operation described in 'ZPASS_UNK_OP_CALL' on that argument
"
}
